/// <reference lib="webworker" />
import { precacheAndRoute } from 'workbox-precaching'

declare const self: ServiceWorkerGlobalScope

self.skipWaiting()
self.addEventListener('activate', (event) => {
  event.waitUntil(self.clients.claim())
})

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST)

// Handle push notifications
self.addEventListener('push', (event) => {
  if (!event.data) return

  const payload = event.data.json() as {
    title: string
    body: string
    tag?: string
    action?: string
    data?: Record<string, unknown>
  }

  if (payload.action === 'dismiss' && payload.tag) {
    // iOS requires showNotification for every push event, so we replace the
    // existing notification (same tag) with a silent one, then close it.
    event.waitUntil(
      self.registration
        .showNotification('', { tag: payload.tag, silent: true })
        .then(() => self.registration.getNotifications({ tag: payload.tag }))
        .then((notifications) => {
          for (const n of notifications) n.close()
        }),
    )
    return
  }

  // iOS doesn't auto-replace notifications by tag, so explicitly close
  // existing ones with the same tag before showing the new one
  const show = payload.tag
    ? self.registration
        .getNotifications({ tag: payload.tag })
        .then((existing) => {
          for (const n of existing) n.close()
        })
        .then(() =>
          self.registration.showNotification(payload.title, {
            body: payload.body,
            icon: '/icon2.png',
            badge: '/icon2.png',
            data: payload.data,
            tag: payload.tag,
          }),
        )
    : self.registration.showNotification(payload.title, {
        body: payload.body,
        icon: '/icon2.png',
        badge: '/icon2.png',
        data: payload.data,
      })

  event.waitUntil(show)
})

// Handle notification clicks
self.addEventListener('notificationclick', (event) => {
  event.notification.close()
  const data = event.notification.data as Record<string, unknown> | undefined
  const url = data?.url as string | undefined

  // External URL — open in a new tab
  if (url) {
    event.waitUntil(self.clients.openWindow(url))
    return
  }

  // Otherwise focus the PWA and forward click data
  event.waitUntil(
    self.clients
      .matchAll({ type: 'window', includeUncontrolled: true })
      .then((clientList) => {
        for (const client of clientList) {
          if ('focus' in client) {
            client.focus()
            client.postMessage({
              type: 'NOTIFICATION_CLICK',
              data: event.notification.data,
            })
            return
          }
        }
        return self.clients.openWindow('/')
      }),
  )
})
