/// <reference lib="webworker" />
import { precacheAndRoute } from 'workbox-precaching'

declare const self: ServiceWorkerGlobalScope

self.skipWaiting()
self.addEventListener('activate', (event) => {
  event.waitUntil(self.clients.claim())
})

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST)

// Handle push notifications
self.addEventListener('push', (event) => {
  if (!event.data) return

  const payload = event.data.json() as {
    title: string
    body: string
    tag?: string
    action?: string
    data?: Record<string, unknown>
  }

  if (payload.action === 'dismiss' && payload.tag) {
    // iOS requires showNotification for every push event, so we replace the
    // existing notification (same tag) with a silent one, then close it.
    event.waitUntil(
      self.registration
        .showNotification('', { tag: payload.tag, silent: true })
        .then(() => self.registration.getNotifications({ tag: payload.tag }))
        .then((notifications) => {
          for (const n of notifications) n.close()
        }),
    )
    return
  }

  event.waitUntil(
    self.registration.showNotification(payload.title, {
      body: payload.body,
      icon: '/icon2.png',
      badge: '/icon2.png',
      data: payload.data,
      tag: payload.tag,
    }),
  )
})

// Handle notification clicks
self.addEventListener('notificationclick', (event) => {
  event.notification.close()

  event.waitUntil(
    self.clients
      .matchAll({ type: 'window', includeUncontrolled: true })
      .then((clientList) => {
        // Try to find an existing PWA window and focus it
        for (const client of clientList) {
          if ('focus' in client) {
            client.focus()
            client.postMessage({
              type: 'NOTIFICATION_CLICK',
              data: event.notification.data,
            })
            return
          }
        }
        // No open window — open a new one
        return self.clients.openWindow('/')
      }),
  )
})
